repos:
-   repo: local
    hooks:
    -   id: swift-format
        name: SwiftFormat
        entry: mint run swiftformat .
        language: system
        types: [swift]
        pass_filenames: false

    -   id: swift-lint
        name: SwiftLint
        entry: mint run swiftlint --strict
        language: system
        types: [swift]
        pass_filenames: false

    -   id: swift-test
        name: Swift Package Tests
        entry: swift test
        language: system
        types: [swift]
        pass_filenames: false
        always_run: true

